backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media

publish_mode: editorial_workflow

collections:
  - name: "portfolio" # Used in routes, e.g., /admin/collections/portfolio
    label: "Portfolio" # Used in the UI
    folder: "src/content/portfolio" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "../../layouts/MarkdownPostLayout.astro",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Ranking", name: "ranking", widget: "number" }
      - { label: "Post Image", name: "hero", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list" default: ["portfolio"] }
      - { label: "Body", name: "body", widget: "markdown" }

